#! /bin/bash
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_13/MuonDataBasicCut_13.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_14/MuonDataBasicCut_14.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_2/MuonDataBasicCut_2.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_3/MuonDataBasicCut_3.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_4/MuonDataBasicCut_4.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_5/MuonDataBasicCut_5.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_6/MuonDataBasicCut_6.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_7/MuonDataBasicCut_7.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_0/MuonDataBasicCut_0.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_1/MuonDataBasicCut_1.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_10/MuonDataBasicCut_10.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_11/MuonDataBasicCut_11.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_12/MuonDataBasicCut_12.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_8/MuonDataBasicCut_8.job
condor_submit /direct/phenix+spin2/beaumim/WAnalysisRun13/AnalysisCode/condor/jobs/job_9/MuonDataBasicCut_9.job
